# Site settings
title: Oddlord - Game Developement
description: Oddlord - Game Developementt
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tommaso Papini
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Game Developer
email: tommy39@gmail.com
twitter_username: TheOddlord
github_username:  oddlord
gplus_username:  lorem_ipsum

# position of the bottom project's img
# values: left, right
# default value: right
projects_starting_side: right

# collections
collections:
  games:
    output: true
    permalink: /:collection/:name
  designs:
    output: true
    permalink: /:collection/:name

# defaults
defaults:
  - scope:
      path: ""
    values:
      author: "Tommaso Papini"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "designs"
    values:
      layout: "design"

sass:
    sass_dir: _sass

exclude: ['package.json', 'src' , 'node_modules']
