# Site settings
title: Oddlord - Game Developement
description: Oddlord - Game Developementt
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tommaso Papini
user_title: Game Developer

twitter_url: https://twitter.com/TheOddlord
linkedin_url: https://www.linkedin.com/in/tommaso-papini/
github_url: https://github.com/oddlord

# enable or disable About Me section
about_me: false

# position of the bottom project's img
# values: left, right
# default value: right
projects_starting_side: right

# collections
collections:
  games:
    output: true
    permalink: /:collection/:name
  designs:
    output: true
    permalink: /:collection/:name

# defaults
defaults:
  - scope:
      path: ""
    values:
      author: "Tommaso Papini"

sass:
    sass_dir: _sass

exclude: ['package.json', 'src' , 'node_modules']
