# Site settings
title: Oddlord - Game Developement
description: Oddlord's Game Developement and Design portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tommaso Papini
user_title: Game Developer

# twitter_url: https://twitter.com/TheOddlord
linkedin_url: https://www.linkedin.com/in/tommaso-papini/
# github_url: https://github.com/oddlord
itch_io_url: https://oddlord.itch.io/
sketchfab_url: https://sketchfab.com/oddlord
artstation_url: https://www.artstation.com/oddlord

# Google-analytics
# google-analytics:
#   id: ""

# enable or disable About Me section
about_me: false

# collections
collections:
  games:
    output: true
    permalink: /:collection/:name
  3d_models:
    output: true
    permalink: /:collection/:name

# defaults
defaults:
  - scope:
      path: ""
    values:
      author: "Tommaso Papini"

sass:
    sass_dir: _sass

exclude: ['package.json', 'src' , 'node_modules']
